### ISSUE TITLE
Warning message appears on the page header

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#114]
1. Upgrade the existing plugin with the updated one
2. Delete all existing sessions and add only 1 session to it.
Result: Go to the upcoming session tab, a warning message appears on the header of the page
![warning messGE](https://user-images.githubusercontent.com/38027574/84127201-8d25cf80-aa5c-11ea-9362-e6c021757324.PNG)

**Comment by manishadayal** [comment]
Fixed

**Comment by sudhanshu0044** [comment]
Working fine
