### ISSUE TITLE
No error message for the scheduling the open session with timed session

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#116]
1. Go to schedule session tab and schedule a timed session
2. Now try to add an open-ended session
Result: Wrong notifications appear instead of notification "open-ended session could not be scheduled with the timed session" or any other information for help.
![open session](https://user-images.githubusercontent.com/38027574/84134438-32917100-aa66-11ea-9497-9d8010ecc6ee.PNG)

**Comment by sudhanshu0044** [comment]
Do you really think the user would be able to schedule an open-ended session after resolving only 1 conflict?
He is not required to delete all the schedules.
![image](https://user-images.githubusercontent.com/38027574/84768339-b52fa880-aff1-11ea-8e78-4391cb60548a.png)

I think conflict is not required to display in a case where user is scheduling an open-ended session

**Comment by manishadayal** [comment]
FIxed.
