### ISSUE TITLE
Language change in recording is not working

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#120]
1. Change a language to languages es, pt_br
2. Now play the recorded session

Result: Recording will open in the English language only.
![es](https://user-images.githubusercontent.com/38027574/84496872-5c979d00-accb-11ea-94bf-aaaa517bc591.PNG)
![pt_br](https://user-images.githubusercontent.com/38027574/84496876-5dc8ca00-accb-11ea-9c2e-384189e275d0.PNG)

**Comment by manishadayal** [comment]
Hi, This issue is not related to Moodle Congrea Plugin.

**Comment by manishadayal** [comment]
Fixed.

**Comment by sudhanshu0044** [comment]
Working
