### ISSUE TITLE
Not able to add sessions on other languages selected on Moodle

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#132]
Steps:
1. Login Moodle and change language pack other than English
2. Now go to Congrea activity
3. Go to Schedule session tab and add session

Result: You would not be able to add sessions if you selected a language other than English
![image](https://user-images.githubusercontent.com/38027574/87000136-eefb6580-c1d1-11ea-813f-a0cc2aeb3f99.png)

Expected result: Users should be able to add sessions while using any language pack on Moodle.

**Comment by manishadayal** [comment]
Fixed and pushed to my repository. Please test at your end.

**Comment by sudhanshu0044** [comment]
Resolved
