### ISSUE TITLE
Warnings while editing the activity setting page

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#144]
If the user goes to the Congrea activity setting page some warnings appear on the top of the page.
![image](https://user-images.githubusercontent.com/38027574/94804369-565b3700-0408-11eb-81fa-017a5262c555.png)

If the user continues on the page and saves it then also some warning appear on the next redirecting page.
![image](https://user-images.githubusercontent.com/38027574/94804512-8e627a00-0408-11eb-8c6f-2410e40dd3ae.png)

**Comment by manishadayal** [comment]
Fixed
