### ISSUE TITLE
Min and max value(min)

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#148]
What are the maximum time and minimum time for the teacher to make the class ready?
![image](https://user-images.githubusercontent.com/38027574/94805882-ba7efa80-040a-11eb-93b9-82ab4bc55645.png)

A range needs to be defined with this feature to make it more useful

**Comment by manishadayal** [comment]
Resolved.

**Comment by manishadayal** [comment]
closed
