### ISSUE TITLE
Issue with preparation time

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#149]
1. Go to the global setting page and set the preparation time to 2 mins
2. Now go to the activity and schedule a session for just after 10-20 mins
Result:
Now go to the "upcoming session tab" there you will see the "Prepare for class" button and as per the setting it should appear 2 mins before from the actual schedule of the session.
![image](https://user-images.githubusercontent.com/38027574/94807034-a1774900-040c-11eb-9777-b321e49722b3.png)

Global setting page
![image](https://user-images.githubusercontent.com/38027574/94807057-a9cf8400-040c-11eb-939b-c74f788d2ca4.png)

The reason it's appearing because in your coding you have configured 30 mins as a default

**Comment by manishadayal** [comment]
fixed
