### ISSUE TITLE
Changing duration on global setting page 

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#150]
1. Go to the global setting page
2. Now change the Preparation time

Result: Default time appearing will also be changed and will be the same as the user has entered

Changing the duration from the user field make the change in the default time appearing near the user field
![image](https://user-images.githubusercontent.com/38027574/94807441-4e51c600-040d-11eb-824d-e2ddefe1548f.png)

**Comment by manishadayal** [comment]
Fixed.
