### ISSUE TITLE
Changing the duration on the activity page

### ISSUE THREAD

**Issue by sudhanshu0044** [congrea/moodle-mod_congrea#151]
1. Go to the activity page
2. Now the enter the value in mins other than the default value
3. Now click on the Save button

Result: Entered new value will not be changed after clicking the save button.
![image](https://user-images.githubusercontent.com/38027574/94808147-46465600-040e-11eb-970c-d484d5497177.png)

**Comment by manishadayal** [comment]
Fixed.
