### ISSUE TITLE
AMOS

### ISSUE THREAD

**Issue by dinism** [congrea/moodle-mod_congrea#85]
I'm a PT-PT translator. Is this OK?
In modle plugins directory:
![imagem](https://user-images.githubusercontent.com/14828021/59550026-f7955400-8f5d-11e9-8995-d7c4bdd1be28.png)

In AMOS
![imagem](https://user-images.githubusercontent.com/14828021/59550041-13005f00-8f5e-11e9-9569-3653eb12a77b.png)

**Comment by jgupta** [comment]
@dinism Thank you so much for reporting this. It should be fixed now.
