### ISSUE TITLE
Strings to translate

### ISSUE THREAD

**Issue by dinism** [congrea/moodle-mod_congrea#98]
Thanks for the great plugin.
I'm a PT-PT translator and there are some strings (congrea activity in Moodle) that are hardcoded to English. Can it be translated?
TIA
![imagem](https://user-images.githubusercontent.com/14828021/78299652-31a40680-752e-11ea-8b63-0f1105ff2aa4.png)

**Comment by dinism** [comment]
This too.
![imagem](https://user-images.githubusercontent.com/14828021/78596916-7d172700-7844-11ea-9321-4cbf9da891b8.png)

**Comment by mavrik** [comment]
Thanks for pointing out dinism,

It would help if you point out all the hardcoded strings that you encounter. We will release it in the next version due in this week itself.

**Comment by dinism** [comment]
These are not strings. All are text HARDCODED to English. All above and below
![imagem](https://user-images.githubusercontent.com/14828021/79673488-20b3f000-81d2-11ea-93c6-bbb99d8dded5.png)
In Release v3.5.1-r4, this is hardcoded too.
![imagem](https://user-images.githubusercontent.com/14828021/79673524-4640f980-81d2-11ea-97c1-984f67772115.png)

**Comment by dinism** [comment]
Thanks for the UPDATE!
